calwoodford/anki_decks

js/js.md
=> Add javascript question

css/css.md
=> Adding CSS Questions

css/css.md
=> Adding more CSS Questions

css/css.md
=> Updated CSS.md

css/css.md
=> Adding more CSS Quesitons

css/css.md
=> Adding CSS Question

css/css.md
=> Update new question css.md

databases/sql.md
=> DDL, DML and TCL flash cards added in the sql.md file

README.md
=> added: gwern link

databases/sql.md
=> Fix typos in sql.md

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md
=> added: no duplicates rule

github/git_commands.md
Add new questions related to following git commands
- `git log`
- `git diff`
- `git switch`
- `git checkout`
<p>
</p>
</details>
<br><br>
=> Add questions related to git commands

js/js.md
=> added JavaScript questions

github/git_commands.md
- git pull
- git clone
- git status
<p>
</p>
</details>
<br><br>
=> Added 3 more flashcards for Git commands.

python/python_commands.md
Added the following python cards:
- What is array slicing?
- What is the `.split()` method used for?
- How can you reverse a list?
<p>
</p>
</details>
<br><br>
=> Added new python cards

github/git_commands.md
- git blame
- git stash
- git reset
- Should be ok, but do let me know if I made some error
<p>
</p>
</details>
<br><br>
=> added: git command questions

databases/sql.md
=> added SQL questions

python/python_commands.md
Added the following questions:
- What is a lambda function?
- What are modules and packages in Python?
- What is the `pandas` library used for in Python?
<p>
</p>
</details>
<br><br>
=> Added 3 cards to Python

software_testing/software_testing.md
=> added software testing questions

data_structure/linked_list.md
<p>
</p>
</details>
<br><br>
---
I have added a new set of questions specifically focused on data structures, with a particular emphasis on linked lists. These new questions aim to provide a comprehensive understanding of this essential data structure concept.
The new file contains three questions:
Definition and explanation of a linked list.
Differences between a singly linked list and a doubly linked list.
Basic operations that can be performed on a linked list.
I believe these additions will enhance the learning experience for users who are seeking to strengthen their knowledge of data structures.
=> Data structure

python/python_commands.md
Added cards related to the pandas library in python
<p>
</p>
</details>
<br><br>
=> Added more python cards

expressjs/expressjs.md
- [x ] You are submitting a maximum of three flashcards.
- [ x] You have verified that the information is correct, via a book, ChatGPT etc.
- [x ] You are using correct grammar and spelling.
- [x ] You have verified the questions do not already exist in the deck.
- [ x] You are using bullet answer format and the question dictates how many bullets are in the answer.
- [ x] You are using the below pattern to add the flashcard:
<p>
</p>
</details>
<br><br>
=> Add a new expess question

python/python_commands.md
- [x ] You are submitting a maximum of three flashcards.
- [ x] You have verified that the information is correct, via a book, ChatGPT etc.
- [ x] You are using correct grammar and spelling.
- [ x] You have verified the questions do not already exist in the deck.
- [ x] You are using bullet answer format and the question dictates how many bullets are in the answer.
- [ x] You are using the below pattern to add the flashcard:
<p>
</p>
</details>
<br><br>
=> Add a new python question

css/css.md
- [ x] You are submitting a maximum of three flashcards.
- [ x] You have verified that the information is correct, via a book, ChatGPT etc.
- [ x] You are using correct grammar and spelling.
- [ x] You have verified the questions do not already exist in the deck.
- [ x] You are using bullet answer format and the question dictates how many bullets are in the answer.
- [ x] You are using the below pattern to add the flashcard:
<p>
</p>
</details>
<br><br>
=> Add a new css question

js/react/react.md
- [Y] You are submitting a maximum of three flashcards.
- [Y] You have verified that the information is correct, via a book, ChatGPT etc.
- [Y] You are using correct grammar and spelling.
- [Y] You have verified the questions do not already exist in the deck.
- [N but not necessary with these questions] You are using bullet answer format and the question dictates how many bullets are in the answer.
- [Y] You are using the below pattern to add the flashcard:
<p>
</p>
</details>
<br><br>
=> 3 react questions added
